/*
 * Copyright (c) 2009-2025 the JdbcUtil authors
 *
 * SPDX-License-Identifier: MIT
 */

package de.schaeuffelhut.jdbc;

import java.sql.Statement;

public enum GeneratedKeys
{
    REPORT( Statement.RETURN_GENERATED_KEYS ),
    IGNORE( Statement.NO_GENERATED_KEYS );

    public final int autoGeneratedKey;

    GeneratedKeys(int autoGeneratedKey)
    {
        this.autoGeneratedKey = autoGeneratedKey;
    }
}
