/*
 * Copyright (c) 2009-2025 the JdbcUtil authors
 *
 * SPDX-License-Identifier: MIT
 */

package de.schaeuffelhut.jdbc;

import java.sql.Statement;

/**
 * Controls whether JDBC should return auto-generated keys after an {@code INSERT}.
 *
 * <p>Used with {@link StatementUtil#execute(GeneratedKeys, StatementProperty, String, StatementInParameter...)}
 * to capture values like primary key IDs generated by the database.</p>
 *
 * <p><strong>Values:</strong></p>
 * <ul>
 *   <li><strong>{@link #REPORT}</strong> — request generated keys
 *       ({@link java.sql.Statement#RETURN_GENERATED_KEYS})</li>
 *   <li><strong>{@link #IGNORE}</strong> — do not request generated keys
 *       ({@link java.sql.Statement#NO_GENERATED_KEYS})</li>
 * </ul>
 *
 * <p><strong>Usage:</strong></p>
 * <pre>{@code
 * // Capture the generated ID
 * Long id = stmtUtil.execute(
 *     GeneratedKeys.REPORT,
 *     stmt -> stmt.getLong(1),           // extract from generated keys ResultSet
 *     "INSERT INTO users (name) VALUES (?)",
 *     StatementParameters.String("Alice")
 * );
 *
 * // Ignore generated keys (faster, default in many cases)
 * int rows = stmtUtil.execute(
 *     GeneratedKeys.IGNORE,
 *     "INSERT INTO logs (message) VALUES (?)",
 *     StatementParameters.String("Login")
 * );
 * }</pre>
 *
 * <p><strong>Performance note:</strong> Use {@link #IGNORE} when you don't need
 * the generated key to avoid the overhead of a second {@link java.sql.ResultSet}.</p>
 *
 * @see StatementUtil#execute(GeneratedKeys, StatementProperty, String, StatementInParameter...)
 * @see java.sql.Statement#RETURN_GENERATED_KEYS
 * @see java.sql.Statement#NO_GENERATED_KEYS
 * @author Friedrich Schäuffelhut
 * @since 2018-06-01
 */
public enum GeneratedKeys {

    /**
     * Request that generated keys be made available.
     */
    REPORT(Statement.RETURN_GENERATED_KEYS),

    /**
     * Do not request generated keys.
     */
    IGNORE(Statement.NO_GENERATED_KEYS);

    final int autoGeneratedKey;

    GeneratedKeys(int autoGeneratedKey) {
        this.autoGeneratedKey = autoGeneratedKey;
    }
}
